<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="theme-color" content="#2e8cc2"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="author" content="Marx JMoura"><meta name="copyright" content="Marx J. Moura"><meta name="description" content="Dashboard is a information management tool that visually tracks, analyzes and displays key performance indicators (KPI)."><title>Admin 4B · Dashboard</title><link rel="icon" href="/docs/favicon.ico"><link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"><link href="/dist/admin4b.min.css?v=2.1.0" rel="stylesheet"><link href="/docs/assets/css/custom.css" rel="stylesheet"></head><body><div class="app"><div class="app-sidebar"><div class="sidebar-header"><svg class="avatar"><use href="/docs/assets/img/faces.svg#john"/></svg><div class="username"><span>John Doe</span> <small>john_doe@email.com</small></div></div><div id="sidebar-nav" class="sidebar-nav"><ul><li><a href="/docs/index.html"><span class="sidebar-nav-icon fa fa-rocket"></span> <span class="sidebar-nav-text">Get started</span></a></li></ul><hr><span class="sidebar-nav-header">Guideline</span><ul><li><a href="#device-controls" data-toggle="collapse"><span class="sidebar-nav-icon fa fa-laptop"></span> <span class="sidebar-nav-text">Device controls</span></a><ul id="device-controls" class="collapse" data-parent="#sidebar-nav"><li><a href="/docs/pages/device-controls/camera.html">Camera</a></li><li><a href="/docs/pages/device-controls/file-manager.html">File manager</a></li></ul></li><li><a href="#forms" data-toggle="collapse"><span class="sidebar-nav-icon fa fa-pencil"></span> <span class="sidebar-nav-text">Forms</span></a><ul id="forms" class="collapse" data-parent="#sidebar-nav"><li><a href="/docs/pages/forms/basic-form.html">Basic form</a></li><li><a href="/docs/pages/forms/tabbed-form.html">Tabbed form</a></li></ul></li><li><a href="#input-controls" data-toggle="collapse"><span class="sidebar-nav-icon fa fa-pencil-square-o"></span> <span class="sidebar-nav-text">Input controls</span></a><ul id="input-controls" class="collapse" data-parent="#sidebar-nav"><li><a href="/docs/pages/input-controls/checkbox.html">Checkbox</a></li><li><a href="/docs/pages/input-controls/input-date.html">Input date</a></li><li><a href="/docs/pages/input-controls/input-suggestion.html">Input suggestion</a></li><li><a href="/docs/pages/input-controls/radio-button.html">Radio button</a></li><li><a href="/docs/pages/input-controls/toggle-switch.html">Toggle switch</a></li></ul></li><li><a href="#layout" data-toggle="collapse"><span class="sidebar-nav-icon fa fa-clone"></span> <span class="sidebar-nav-text">Layout</span></a><ul id="layout" class="collapse" data-parent="#sidebar-nav"><li><a href="/docs/pages/layout/sidebar.html">Sidebar</a></li><li><a href="/docs/pages/layout/spinner.html">Spinner</a></li><li><a href="/docs/pages/layout/table.html">Table</a></li></ul></li><li><a href="#reference" data-toggle="collapse"><span class="sidebar-nav-icon fa fa-code"></span> <span class="sidebar-nav-text">Reference</span></a><ul id="reference" class="collapse" data-parent="#sidebar-nav"><li><a href="/docs/pages/reference/callout.html">Callout</a></li><li><a href="/docs/pages/reference/code-highlight.html">Code highlight</a></li></ul></li></ul><hr><span class="sidebar-nav-header">Content</span><ul><li><a href="/docs/pages/content/chat.html"><span class="sidebar-nav-icon fa fa-comments"></span> <span class="sidebar-nav-text">Chat</span></a></li><li><a href="/docs/pages/content/dashboard.html"><span class="sidebar-nav-icon fa fa-pie-chart"></span> <span class="sidebar-nav-text">Dashboard</span></a></li><li><a href="#pages" data-toggle="collapse"><span class="sidebar-nav-icon fa fa-file"></span> <span class="sidebar-nav-text">Pages</span></a><ul id="pages" class="collapse" data-parent="#sidebar-nav"><li><a href="/docs/pages/content/blank-page.html" class="sidebar-nav-link">Blank page</a></li><li><a href="/docs/pages/content/error-404.html" class="sidebar-nav-link">Error 404</a></li><li><a href="/docs/pages/content/error-500.html" class="sidebar-nav-link">Error 500</a></li></ul></li><li><a href="/docs/pages/content/settings.html"><span class="sidebar-nav-icon fa fa-cog"></span> <span class="sidebar-nav-text">Settings</span></a></li><li><a href="/docs/pages/content/timeline.html"><span class="sidebar-nav-icon fa fa-clock-o"></span> <span class="sidebar-nav-text">Timeline</span></a></li></ul><hr><ul><li><a href="/docs/pages/content/signin.html"><span class="sidebar-nav-icon fa fa-power-off"></span> <span class="sidebar-nav-text">Log out</span></a></li></ul></div></div><div class="app-content"><div class="content-header"><nav class="navbar navbar-expand navbar-light bg-white"><div class="navbar-brand"><button type="button" class="btn btn-sidebar" data-toggle="sidebar"><i class="fa fa-bars"></i></button> <span class="pr-2">Admin 4B</span> <a href="https://github.com/marxjmoura/admin4b" class="text-dark decoration-none" data-toggle="tooltip" data-placement="right" title="Fork me on GitHub"><i class="fa fa-github"></i></a></div><ul class="navbar-nav ml-auto"><li class="nav-item dropdown"><a href="#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="badge badge-pill badge-primary">3</span> <i class="fa fa-bell-o"></i></a><div class="dropdown-menu dropdown-menu-right"><a href="/docs/pages/content/notification.html" class="dropdown-item"><small class="dropdown-item-title">Lorem ipsum (today)</small><br><div>Lorem ipsum dolor sit amet...</div></a><div class="dropdown-divider"></div><a href="/docs/pages/content/notification.html" class="dropdown-item"><small class="text-muted">Lorem ipsum (yesterday)</small><br><div>Lorem ipsum dolor sit amet...</div></a><div class="dropdown-divider"></div><a href="/docs/pages/content/notification.html" class="dropdown-item"><small class="text-muted">Lorem ipsum (12/25/2017)</small><br><div>Lorem ipsum dolor sit amet...</div></a><div class="dropdown-divider"></div><a href="/docs/pages/content/notifications.html" class="dropdown-item dropdown-link">See all notifications</a></div></li></ul></nav><nav><ol class="breadcrumb"><li class="breadcrumb-item">Dashboard</li></ol></nav></div><div class="content-body"><div class="container"><div class="card"><div class="card-body"><di class="row"><div class="col-12 col-lg-8"><div class="form-group"><p class="text-muted text-center">Sales per month</p><canvas id="sales" height="120"></canvas></div></div><div class="col-12 col-lg-4"><p class="text-muted text-center">Last sales</p><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th><small>Order ID</small></th><th><small>Payment</small></th><th><small>Amount</small></th></tr></thead><tbody><tr><td>9390</td><td><span class="badge badge-success">cash</span></td><td>$12.25</td></tr><tr><td>9183</td><td><span class="badge badge-secondary">credit card</span></td><td>$80.75</td></tr><tr><td>4640</td><td><span class="badge badge-primary">paypal</span></td><td>$105.60</td></tr><tr><td>2442</td><td><span class="badge badge-secondary">credit card</span></td><td>$32.50</td></tr></tbody><tfoot><tr><td colspan="3" class="text-center pt-3"><a href="#">See all sales</a></td></tr></tfoot></table></div></div></di></div></div><div class="row"><div class="col-12 col-lg-6"><div class="card"><div class="card-body"><p class="text-muted text-center">Payment methods usage</p><canvas id="pay-methods" height="120"></canvas></div></div></div><div class="col-12 col-lg-6"><div class="card"><div class="card-body"><p class="text-muted text-center">Cash flow</p><canvas id="cash-flow" height="120"></canvas></div></div></div></div><div class="source-code"><a href="#dashboard" data-toggle="collapse"><i class="fa fa-code"></i> Source code</a><div id="dashboard" class="collapse"><div class="nav nav-tabs"><a href="#dashboard-html" class="active" data-toggle="tab">HTML</a> <a href="#dashboard-js" data-toggle="tab">JavaScript</a></div><div class="tab-content"><div id="dashboard-html" class="tab-pane active"><pre><code class="html">&lt;div class&#x3D;&quot;card&quot;&gt;
  &lt;div class&#x3D;&quot;card-body&quot;&gt;
    &lt;di class&#x3D;&quot;row&quot;&gt;
      &lt;div class&#x3D;&quot;col-12 col-lg-8&quot;&gt;
        &lt;div class&#x3D;&quot;form-group&quot;&gt;
          &lt;p class&#x3D;&quot;text-muted text-center&quot;&gt;
            Sales per month
          &lt;/p&gt;
          &lt;canvas id&#x3D;&quot;sales&quot; height&#x3D;&quot;120&quot;&gt;&lt;/canvas&gt;
        &lt;/div&gt;
      &lt;/div&gt;
      &lt;div class&#x3D;&quot;col-12 col-lg-4&quot;&gt;
        &lt;p class&#x3D;&quot;text-muted text-center&quot;&gt;
          Last sales
        &lt;/p&gt;
        &lt;div class&#x3D;&quot;table-responsive&quot;&gt;
          &lt;table class&#x3D;&quot;table table-sm mb-0&quot;&gt;
            &lt;thead&gt;
              &lt;tr&gt;
                &lt;th&gt;&lt;small&gt;Order ID&lt;/small&gt;&lt;/th&gt;
                &lt;th&gt;&lt;small&gt;Payment&lt;/small&gt;&lt;/th&gt;
                &lt;th&gt;&lt;small&gt;Amount&lt;/small&gt;&lt;/th&gt;
              &lt;/tr&gt;
            &lt;/thead&gt;
            &lt;tbody&gt;
              &lt;tr&gt;
                &lt;td&gt;9390&lt;/td&gt;
                &lt;td&gt;
                  &lt;span class&#x3D;&quot;badge badge-success&quot;&gt;cash&lt;/span&gt;
                &lt;/td&gt;
                &lt;td&gt;$12.25&lt;/td&gt;
              &lt;/tr&gt;
              &lt;tr&gt;
                &lt;td&gt;9183&lt;/td&gt;
                &lt;td&gt;
                  &lt;span class&#x3D;&quot;badge badge-secondary&quot;&gt;credit card&lt;/span&gt;
                &lt;/td&gt;
                &lt;td&gt;$80.75&lt;/td&gt;
              &lt;/tr&gt;
              &lt;tr&gt;
                &lt;td&gt;4640&lt;/td&gt;
                &lt;td&gt;
                  &lt;span class&#x3D;&quot;badge badge-primary&quot;&gt;paypal&lt;/span&gt;
                &lt;/td&gt;
                &lt;td&gt;$105.60&lt;/td&gt;
              &lt;/tr&gt;
              &lt;tr&gt;
                &lt;td&gt;2442&lt;/td&gt;
                &lt;td&gt;
                  &lt;span class&#x3D;&quot;badge badge-secondary&quot;&gt;credit card&lt;/span&gt;
                &lt;/td&gt;
                &lt;td&gt;$32.50&lt;/td&gt;
              &lt;/tr&gt;
            &lt;/tbody&gt;
            &lt;tfoot&gt;
              &lt;tr&gt;
                &lt;td colspan&#x3D;&quot;3&quot; class&#x3D;&quot;text-center pt-3&quot;&gt;
                  &lt;a href&#x3D;&quot;#&quot;&gt;See all sales&lt;/a&gt;
                &lt;/td&gt;
              &lt;/tr&gt;
            &lt;/tfoot&gt;
          &lt;/table&gt;
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
  &lt;div class&#x3D;&quot;row&quot;&gt;
    &lt;div class&#x3D;&quot;col-12 col-lg-6&quot;&gt;
      &lt;div class&#x3D;&quot;card&quot;&gt;
        &lt;div class&#x3D;&quot;card-body&quot;&gt;
          &lt;p class&#x3D;&quot;text-muted text-center&quot;&gt;
            Payment methods usage
          &lt;/p&gt;
          &lt;canvas id&#x3D;&quot;pay-methods&quot; height&#x3D;&quot;120&quot;&gt;&lt;/canvas&gt;
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/div&gt;
    &lt;div class&#x3D;&quot;col-12 col-lg-6&quot;&gt;
      &lt;div class&#x3D;&quot;card&quot;&gt;
        &lt;div class&#x3D;&quot;card-body&quot;&gt;
          &lt;p class&#x3D;&quot;text-muted text-center&quot;&gt;
            Cash flow
          &lt;/p&gt;
          &lt;canvas id&#x3D;&quot;cash-flow&quot; height&#x3D;&quot;120&quot;&gt;&lt;/canvas&gt;
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
</code></pre></div><div id="dashboard-js" class="tab-pane"><pre><code class="js">// Chart library available at <a href="https://www.chartjs.org">https://www.chartjs.org</a>.</code></pre></div></div></div></div></div></div></div></div><script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.min.js"></script><script src="/dist/admin4b.min.js?v=2.1.0"></script><script src="/docs/assets/js/docs.js"></script><script src="/docs/assets/js/chart.js"></script></body></html>