<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="theme-color" content="#2e8cc2"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="author" content="Marx JMoura"><meta name="copyright" content="Marx J. Moura"><meta name="description" content="Sign up page allow users to create an account and enter first time credentials details."><title>Admin 4B · Sign up</title><link rel="icon" href="/docs/favicon.ico"><link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"><link href="/dist/admin4b.min.css?v=2.1.0" rel="stylesheet"><link href="/docs/assets/css/custom.css" rel="stylesheet"></head><body><div class="app"><div class="app-content"><div class="content-body"><div class="page-sign sign-up"><div class="container pb-0 mb-0"><div class="source-code"><a href="#settings" data-toggle="collapse"><i class="fa fa-code"></i> Source code</a><div id="settings" class="collapse"><pre><code class="html">&lt;div class&#x3D;&quot;page-sign&quot;&gt;
  &lt;div class&#x3D;&quot;container-sign&quot;&gt;
    &lt;div class&#x3D;&quot;card&quot;&gt;
      &lt;div class&#x3D;&quot;card-header&quot;&gt;
        &lt;img src&#x3D;&quot;admin4b.svg&quot;&gt;
        &lt;h1&gt;Welcome&lt;/h1&gt;
        &lt;span&gt;Sign up your account for free&lt;/span&gt;
      &lt;/div&gt;
      &lt;div class&#x3D;&quot;card-body&quot;&gt;
        &lt;div class&#x3D;&quot;row&quot;&gt;
          &lt;div class&#x3D;&quot;col&quot;&gt;
            &lt;div class&#x3D;&quot;form-group&quot;&gt;
              &lt;label&gt;First name&lt;/label&gt;
              &lt;input type&#x3D;&quot;text&quot; class&#x3D;&quot;form-control&quot;&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class&#x3D;&quot;col&quot;&gt;
            &lt;div class&#x3D;&quot;form-group&quot;&gt;
              &lt;label&gt;Last name&lt;/label&gt;
              &lt;input type&#x3D;&quot;text&quot; class&#x3D;&quot;form-control&quot;&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/div&gt;
        &lt;div class&#x3D;&quot;form-group&quot;&gt;
          &lt;label&gt;E-mail&lt;/label&gt;
          &lt;input type&#x3D;&quot;text&quot; class&#x3D;&quot;form-control&quot;&gt;
        &lt;/div&gt;
        &lt;div class&#x3D;&quot;form-group&quot;&gt;
          &lt;label&gt;Password&lt;/label&gt;
          &lt;input type&#x3D;&quot;password&quot; class&#x3D;&quot;form-control&quot;&gt;
        &lt;/div&gt;
        &lt;div class&#x3D;&quot;form-group d-flex&quot;&gt;
          &lt;label class&#x3D;&quot;checkbox&quot;&gt;
            &lt;input type&#x3D;&quot;checkbox&quot;&gt;
            &lt;span class&#x3D;&quot;check-mark&quot;&gt;&lt;/span&gt; I agree to&amp;nbsp; &lt;a href&#x3D;&quot;#&quot;&gt;terms&lt;/a&gt;
          &lt;/label&gt;
          &lt;a href&#x3D;&quot;/&quot; class&#x3D;&quot;btn btn-primary ml-auto&quot;&gt;
            Sign up
          &lt;/a&gt;
        &lt;/div&gt;
      &lt;/div&gt;
      &lt;div class&#x3D;&quot;card-footer&quot;&gt;
        &lt;p class&#x3D;&quot;text-muted&quot;&gt;Already have an account?&lt;/p&gt;
        &lt;a href&#x3D;&quot;signin.html&quot;&gt;Sign in now&lt;/a&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;
</code></pre></div></div></div><div class="container-sign"><div class="card"><div class="card-header"><img src="/docs/assets/brand/admin4b.svg"><h1>Welcome</h1><span>Sign up your account for free</span></div><div class="card-body"><div class="row"><div class="col"><div class="form-group"><label>First name</label> <input type="text" class="form-control"></div></div><div class="col"><div class="form-group"><label>Last name</label> <input type="text" class="form-control"></div></div></div><div class="form-group"><label>E-mail</label> <input type="text" class="form-control"></div><div class="form-group"><label>Password</label> <input type="password" class="form-control"></div><div class="form-group d-flex"><label class="checkbox"><input type="checkbox"> <span class="check-mark"></span> I agree to&nbsp; <a href="#">terms</a></label> <a href="/" class="btn btn-primary ml-auto">Sign up</a></div></div><div class="card-footer"><p class="text-muted">Already have an account?</p><a href="/docs/pages/content/signin.html">Sign in now</a></div></div></div></div></div></div></div><script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.min.js"></script><script src="/dist/admin4b.min.js?v=2.1.0"></script><script src="/docs/assets/js/docs.js"></script></body></html>